namespace PartitionInfo;

table PartitionLog {
    graph_metadata: GraphMetadata;
    partition_configuration: PartitionConfiguration;
    runtime: RunTime;
    memory_consumption: MemoryConsumption;
    metrics: PartitionMetrics;
}

table GraphMetadata {
    filename: string;
    num_nodes: ulong;
    num_edges: ulong;
}

table PartitionConfiguration {
    k: uint;
    seed: int;
    batch_size: ulong;
    model_mode:int; //-1 = minimal mode
    alpha:int; // 0 = batch alpha, 1 = static alpha, 2 = dynamic alpha
    max_buffer_size: ulong;
    bb_ratio:uint;
    buffer_score_type:int;
    d_max:uint;
    haa_beta:float;
    haa_theta:float;
    cbs_theta:float;
    buffer_neighbor_weight:float;
    batch_frontier_weight:float;
    num_streams_passes:int;
    restream_number:int;
    restream_include_high_degree_nodes:bool;
    restream_vcycle:bool;
    ghost_neighbors_enabled:bool;
    ghost_weight:float;
    sep_batch_marker:bool;
    batch_extraction_strategy:int;
    max_active_batches:uint;
    max_input_q_size:uint;
    alt_thread_queue:bool;
    collect_locality_metrics:bool;
}

table RunTime {
    io_time: double;
    partition_time: double;
    model_construction_time: double;
    mapping_time: double;
    total_time: double;
}

table PartitionMetrics{
    edge_cut: int;
    vertex_cut: uint;
    replicas: uint;
    replication_factor: double;
    balance: double;
    internal_edge_ratio: double;
    neighbor_coverage: double;
    conductance: double;
}

table MemoryConsumption{
    max_rss: long;
}

root_type PartitionLog;
